name: type check
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  steep:
    name: steep
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - run: bundle exec rbs install
      - run: bundle exec steep validate
      - run: bundle exec steep check
