name: test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15.4-bookworm
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conference_app_test
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/conference_app_test
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - run: bundle exec rails db:schema:load
      - run: bundle exec rails tailwindcss:build
      - run: bundle exec rspec
